environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "32"

platform: x86

configuration: Release

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # Utilise pre-installed MinGw for make
  - ps: $env:PATH = 'C:\MinGW\msys\1.0\bin;C:\MinGW\mingw32\bin;C:\MinGW\bin;' + $env:PATH

  # As AppVeyor has multiple python install, check which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  # Install / check python dependencies (v3.2 has VC++ redistributable dependencies)
  - cmd: pip install simplegeneric 
  - cmd: pip install pgzero 
  - cmd: pip install pynsist
  - cmd: pip install -r requirements.txt

  # Check installed packages
  - cmd: pip freeze
  - cmd: python -c "import PyQt5"
  - cmd: python -c "import PyQt5.Qsci"
  - cmd: python -c "import PyQt5.QtChart"

  # Build mu using pynsist, rename dist folder and executable with timestamp
  # 64bit
  - cmd: pynsist win_installer64.cfg
  - ps: Rename-Item -path .\build upload64
  - cmd: dir upload64\nsis
  - ps: Rename-Item .\upload64\nsis\mu_1.0.0b15.exe mu_$(get-date -f yyyy-MM-dd_HH_mm)_$($env:APPVEYOR_REPO_BRANCH)_$($env:APPVEYOR_REPO_COMMIT.subString(0,7))_64bit.exe
  # 32bit
  - cmd: pynsist win_installer32.cfg
  - ps: Rename-Item -path .\build upload32
  - cmd: dir upload32\nsis
  - ps: Rename-Item .\upload32\nsis\mu_1.0.0b15.exe mu_$(get-date -f yyyy-MM-dd_HH_mm)_$($env:APPVEYOR_REPO_BRANCH)_$($env:APPVEYOR_REPO_COMMIT.subString(0,7))_32bit.exe

# Not a project with an msbuild file, build done at install.
build: None

# Makefiles support provided by MinGW, which does POSIX translations, so run tests natively as well
test_script:
  - cmd: make coverage 

# Push artifacts to s3 bucket and list all
before_deploy:
  - ps: Get-ChildItem .\upload64\nsis\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName mu-s3-deployment }
  - ps: Get-ChildItem .\upload32\nsis\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName mu-s3-deployment }
  - ps: foreach($artifactName in $artifacts.keys) { $artifacts[$artifactName] }

# Deploy build to Amazon S3 bucket
deploy:
  name: mu-s3-deployment
  provider: S3
  access_key_id: AKIAJYJV7NN6HVHCX5NQ
  secret_access_key:
    secure: PlLCQKTcf9IzBXpEnXUxbJifb0usS7qcghnM0VxBTX0IL3C975JPidrYjP39ge7P
  bucket: mu-builds
  region: eu-west-2
  set_public: true
  folder: windows
  on:
    branch: [master]
